# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About Me
    url: '#about'
    weight: 10
  - name: Skills
    url: '#skills'
    weight: 20
  - name: Projects
    url: '#projects'
    weight: 30
  - name: Experience
    url: '#experience'
    weight: 40
  - name: Accomplishments
    url: '#accomplishments'
    weight: 50
  - name: Contact
    url: '#contact'
    weight: 60
  # - name: Résumé
  #   url: media/sethnielsen_resume.pdf
  #   weight: 90